# WARNING: This file is deployed from template. Raise a pull request against image-template to change.
version: '2'

services:
   image-template:
     build: .
     container_name: "image-template" #your repo name.
     hostname: "image-template"
     environment:
       - KEY=VALUE
       - KEY2=${ENV_VAR_ON_HOST}
